# Generated by Django 4.2.7 on 2024-02-18 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_course_options_alter_lesson_options'),
        ('users', '0002_alter_user_options_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_of_payment', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(default=11)),
                ('payment_method', models.CharField(default='transfer', max_length=11)),
                ('course', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='materials.course')),
                ('lesson', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='materials.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
