# Generated by Django 4.2.7 on 2024-02-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_data_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='data_of_payment',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
