# Generated by Django 4.2.7 on 2024-03-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
