# Generated by Django 4.2.7 on 2024-02-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_lesson_video_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'lesson', 'verbose_name_plural': 'lessons'},
        ),
    ]
