# Generated by Django 4.2.7 on 2024-02-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
