# Generated by Django 4.2.7 on 2024-03-21 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_payment_course', models.CharField(max_length=400)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course')),
            ],
            options={
                'verbose_name': 'payment-course',
                'verbose_name_plural': 'payments-courses',
            },
        ),
    ]
