# Generated by Django 4.2.7 on 2024-03-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_payment_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_course',
            new_name='PaymentCourse',
        ),
    ]
