# Generated by Django 4.2.7 on 2024-03-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_rename_payment_course_paymentcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentcourse',
            name='url_payment_course',
            field=models.URLField(default='', max_length=333),
        ),
        migrations.AlterField(
            model_name='paymentcourse',
            name='id_payment_course',
            field=models.CharField(max_length=333),
        ),
    ]
