# Generated by Django 4.2.7 on 2024-03-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_course_price_paymentcourse_url_payment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcourse',
            name='id_payment_course',
            field=models.CharField(blank=True, max_length=333, null=True),
        ),
    ]
